#include<stdio.h>
#include<conio.h>
void main()
{
int vec[24],t,p,i,x,y,m,w,q;
clrscr();
x=2;y=1;
for(i=0;i<=24;i++)
{printf("M");
scanf("%c",&m);
}
for(i=0;i<=78;i++)
{gotoxy(x++,y);
printf("M");
scanf("%c",&m);
}
t=2;p=2;
for(i=0;i<=80;i++)
{gotoxy(t++,p);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=22;i++)
{gotoxy(t-81,p++);
printf("M");
scanf("%c",&m);
}
w=2;q=3;
for(i=0;i<=79;i++)
{gotoxy(w++,q);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=21;i++)
{gotoxy(w-79,q++);
printf("M");
scanf("%c",&m);
}
w=3;q=4;
for(i=0;i<=79;i++)
{gotoxy(w++,q);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=20;i++)
{gotoxy(w-79,q++);
printf("M");
scanf("%c",&m);
}
w=4;q=5;
for(i=0;i<=79;i++)
{gotoxy(w++,q);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=19;i++)
{gotoxy(w-79,q++);
printf("M");
scanf("%c",&m);
}
w=5;q=6;
for(i=0;i<=79;i++)
{gotoxy(w++,q);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=18;i++)
{gotoxy(w-79,q++);
printf("M");
scanf("%c",&m);
}
w=5;q=6;
for(i=0;i<=79;i++)
{gotoxy(w++,q);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=17;i++)
{gotoxy(w-79,q++);
printf("M");
scanf("%c",&m);
}
w=6;q=7;
for(i=0;i<=79;i++)
{gotoxy(w++,q);
printf("M");
scanf("%c",&m);
}
for(i=0;i<=16;i++)
{gotoxy(w-79,q++);
printf("M");
scanf("%c",&m);
}
}













